#!/bin/bash

if which redo >/dev/null; then
    REDO="redo -j2"
else
    REDO=./.do/do
fi

if [ ! -x ./ndg ]; then
	$REDO
fi

if [ $# -gt 0 ] ;  then
	LD_LIBRARY_PATH=./libraries/libtcod-1.5.0 ./ndg 1
else
	LD_LIBRARY_PATH=./libraries/libtcod-1.5.0 ./ndg
fi