#!/bin/bash

if which redo >/dev/null; then
    REDO="redo -j2"
else
    REDO=./.do/do
fi

if [ $# -gt 0 ] ;  then
	$REDO && LD_LIBRARY_PATH=./libraries/libtcod-1.5.0 ./ndg 1
else
	$REDO && LD_LIBRARY_PATH=./libraries/libtcod-1.5.0 ./ndg
fi